# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJhbsAtn0axI9MRa1FfiuMzWjvr6JB4W

#Project ML
#Customer_Segmentation by using K-Means Clustering

#Importing independencies
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("/content/Mall_Customers.csv")

df.head()

df.info()

df['Gender'].value_counts()

df.isnull().sum()

df.shape

"""#Choosing the AnnualIncome and Spending SCore(1-100)"""

X = df.iloc[:,[3,4]].values

X

"""#Choose Number of Clusters
#WCSS(With Clusters Sum of Squares)

"""

from sklearn.cluster import KMeans

wcss=  []
for k in range(1,11):
  kmeans = KMeans(n_clusters = k,init="k-means++")
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

wcss

plt.plot(range(1,11),wcss)
plt.title("The Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt

"""#We need to chooose k=5"""

kmeans = KMeans(n_clusters=5,init="k-means++",random_state=0)
y_kmeans = kmeans.fit_predict(X)

y_kmeans

"""#Visulazie the all the Clusters

#X[y_means==0,0]-->This is mY  X-coordinare,X[y_means==0,1] --> this is my Y coordinate
#y_means ==0,0 -> first 0 is my cluster second 0 is my annual_income column
#y_means ==01,0 -> first 1 is my cluster second 0 is my annual_income column
#y_means ==2,0 -> first 2 is my cluster second 0 is my annual_income column
#y_means ==3,0 -> first 3 is my cluster second 0 is my annual_income column
#y_means ==4,0 -> first 4 is my cluster second 0 is my annual_income column
----
#y_means ==0,1 -> first 0 is my cluster second 1 is my spending score column
#y_means ==01,1 -> first 1 is my cluster second 1 is my spending score column
#y_means ==2,1 -> first 2 is my cluster second 1 is my spending score column
#y_means ==3,1 -> first 3 is my cluster second 1 is my spending score column
#y_means ==4,1 -> first 4 is my cluster second 1 is my spending score column

#5 Clusters is 0,1,2,3,4

#Plotting the centeroids
"""

plt.figure(figsize=(8,8))
plt.scatter(X[y_kmeans==0,0],X[y_kmeans==0,1],s=100,c="red",label="Cluster 1")
plt.scatter(X[y_kmeans==1,0],X[y_kmeans==1,1],s=100,c="green",label="Cluster 2")
plt.scatter(X[y_kmeans==2,0],X[y_kmeans==2,1],s=100,c="blue",label="Cluster 3")
plt.scatter(X[y_kmeans==3,0],X[y_kmeans==3,1],s=100,c="brown",label="Cluster 4")
plt.scatter(X[y_kmeans==4,0],X[y_kmeans==4,1],s=100,c="orange",label="Cluster 5")

#Plotting the centroids

plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=100, c="black", label="Centroids")
plt.title("Clusters of Customers")
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.show()

"""#plt.scatter(x, y, s=SIZE, c=COLOR, marker=SHAPE, label="Cluster 1")
#x: The x-coordinates of the data points.
#y: The y-coordinates of the data points.
#s: The size of each marker (default is s=20).
#c: The color of the markers.
#marker: The shape of the marker (e.g., 'o' for circles, 's' for #squares).
#label: The label for the legend.

"""

